Add Guy Waldman to README
MichalPorag/IsraelTechWriters pull request #7
Opened 2021-04-07 14:21 UTC by guywaldman

2021-04-07 14:29 UTC, guywaldman commented
P.S. This is a great initiative, kudos for doing this 👏

2021-04-07 15:01 UTC, MichalPorag requested changes

2021-04-07 15:01 UTC, MichalPorag commented on README.md
> +* [Guy Waldman](https://guywaldman.dev/): Full stack (mostly front end). Writing language: en.
Please change to ", Front end".

2021-04-08 05:55 UTC, MichalPorag commented
Please resolve conflicts.

2021-04-08 09:33 UTC, merged